sonar.projectKey=jhl-labs_test-cli
sonar.projectName=jhl-labs/test-cli
sonar.sources=.
sonar.exclusions=**/.git/**,**/node_modules/**,**/reports/**,**/coverage/**,**/dist/**,**/build/**,**/.next/**,**/vendor/**
